### PR TITLE
Added Waterlogging Support

### PR DESCRIPTION
**Pull request by JSBOfficial**
All items are now waterlogged - Needs performance test.

### CODE REVIEW

**Comment by JSBOfficial** [comment]
I believe every item should be waterlogged but needs something for contradicting items like lava bucket, magmacream and etc. Maybe not allowing it to be placed underwater or adding sizzling particles?

**Comment by Ferdzz** [comment]
Looking good! I'll have a deeper look at this tonight

**Comment by Ferdzz** [comment]
@JSBOfficial Hi, I've done some testing on my end and I would like if you could check the following:
- Upgrading from an old world with items that are already placed should not cause them to be waterlogged by default. Please check if the default value can be set to false
- I haven't looked into what waterlogged items do in the base game, are they only supposed to cover *source* blocks? On my testing, it looks like all the placeable items only get waterlogged in source blocks

**Comment by JSBOfficial** [comment]
@Ferdzz Hello, My understading about waterlogging is just it fixes the item's rendering underwater. So basically because every block in placeable items are custom shapes and placeable underwater I just added the fix to the source block which automatically fixes all the placeable items block rendering underwater.

**Comment by Ferdzz** [comment]
@JSBOfficial Ah I see, I didn't understand what waterlogged actually was for. Could you just check that the default value for when the world is updated to the latest version? Items shouldn't be waterlogged by default

**Comment by JSBOfficial** [comment]
Hello again, I tried studying it and tested some ways but it always sprouted some logical issues. I can't make the feature consistent and controlable per block but I don't see any world problems arising.

**Comment by Ferdzz** [comment]
@JSBOfficial Thank you, please let me know what you find when looking at the chest implementation

**Comment by Eugen1344** [comment]
@Ferdzz what about this feature? Will it be merged?

**Comment by Ferdzz** [comment]
@Eugen1344 not as it is now. This PR is 2 years old and full of conflicts. It would need to be reviewed for 1.16 too

**Comment by Ferdzz** [comment]
Closing due to inactivity

**Pull request closed without merging**
